alter table VIDEO4_ORDER_LINE add constraint FK_VIDEO4_ORDER_LINE_ORDER foreign key (ORDER_ID) references VIDEO4_ORDER(ID);
alter table VIDEO4_ORDER_LINE add constraint FK_VIDEO4_ORDER_LINE_PRODUCT foreign key (PRODUCT_ID) references VIDEO4_PRODUCT(ID);
create index IDX_VIDEO4_ORDER_LINE_ORDER on VIDEO4_ORDER_LINE (ORDER_ID);
create index IDX_VIDEO4_ORDER_LINE_PRODUCT on VIDEO4_ORDER_LINE (PRODUCT_ID);
