alter table BICYCLEAPPS2_ORDER add constraint FK_BICYCLEAPPS2_ORDER_CLIENT foreign key (CLIENT_ID) references BICYCLEAPPS2_CLIENT(ID);
alter table BICYCLEAPPS2_ORDER add constraint FK_BICYCLEAPPS2_ORDER_MECHANIC foreign key (MECHANIC_ID) references BICYCLEAPPS2_MECHANIC(ID);
create index IDX_BICYCLEAPPS2_ORDER_CLIENT on BICYCLEAPPS2_ORDER (CLIENT_ID);
create index IDX_BICYCLEAPPS2_ORDER_MECHANIC on BICYCLEAPPS2_ORDER (MECHANIC_ID);
