alter table BICYCLEAPPS2_MECHANIC add constraint FK_BICYCLEAPPS2_MECHANIC_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_BICYCLEAPPS2_MECHANIC_USER on BICYCLEAPPS2_MECHANIC (USER_ID);
