-- begin HRMANAGEMENT_ASSIGN_DN
alter table HRMANAGEMENT_ASSIGN_DN add constraint FK_HRMANAGEMENT_ASSIGN_DN_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
alter table HRMANAGEMENT_ASSIGN_DN add constraint FK_HRMANAGEMENT_ASSIGN_DN_SELECT_EMPLOYEE foreign key (SELECT_EMPLOYEE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create unique index IDX_HRMANAGEMENT_ASSIGN_DN_UNIQ_EMAIL_ID on HRMANAGEMENT_ASSIGN_DN (EMAIL_ID) ^
create index IDX_HRMANAGEMENT_ASSIGN_DN_CODE on HRMANAGEMENT_ASSIGN_DN (CODE_ID)^
create index IDX_HRMANAGEMENT_ASSIGN_DN_SELECT_EMPLOYEE on HRMANAGEMENT_ASSIGN_DN (SELECT_EMPLOYEE_ID)^
-- end HRMANAGEMENT_ASSIGN_DN
-- begin HRMANAGEMENT_ADD_EMPLOYEE
alter table HRMANAGEMENT_ADD_EMPLOYEE add constraint FK_HRMANAGEMENT_ADD_EMPLOYEE_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_HRMANAGEMENT_ADD_EMPLOYEE_IMAGE_FILE on HRMANAGEMENT_ADD_EMPLOYEE (IMAGE_FILE_ID)^
-- end HRMANAGEMENT_ADD_EMPLOYEE
-- begin HRMANAGEMENT_NOMINEES_DETAILS
alter table HRMANAGEMENT_NOMINEES_DETAILS add constraint FK_HRMANAGEMENT_NOMINEES_DETAILS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_NOMINEES_DETAILS_CODE on HRMANAGEMENT_NOMINEES_DETAILS (CODE_ID)^
-- end HRMANAGEMENT_NOMINEES_DETAILS
-- begin HRMANAGEMENT_PERSONAL_DETAILS
alter table HRMANAGEMENT_PERSONAL_DETAILS add constraint FK_HRMANAGEMENT_PERSONAL_DETAILS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_PERSONAL_DETAILS_CODE on HRMANAGEMENT_PERSONAL_DETAILS (CODE_ID)^
-- end HRMANAGEMENT_PERSONAL_DETAILS
-- begin HRMANAGEMENT_QUALIFICATION_DETAILS
alter table HRMANAGEMENT_QUALIFICATION_DETAILS add constraint FK_HRMANAGEMENT_QUALIFICATION_DETAILS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_QUALIFICATION_DETAILS_CODE on HRMANAGEMENT_QUALIFICATION_DETAILS (CODE_ID)^
-- end HRMANAGEMENT_QUALIFICATION_DETAILS
-- begin HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING
alter table HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING add constraint FK_HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING_CODE on HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING (CODE_ID)^
-- end HRMANAGEMENT_TRAINING_DETAILS_PRIOR_TO_JOINING

-- begin HRMANAGEMENT_VERIFY_EMP_STATUS
alter table HRMANAGEMENT_VERIFY_EMP_STATUS add constraint FK_HRMANAGEMENT_VERIFY_EMP_STATUS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_VERIFY_EMP_STATUS_CODE on HRMANAGEMENT_VERIFY_EMP_STATUS (CODE_ID)^
-- end HRMANAGEMENT_VERIFY_EMP_STATUS
-- begin HRMANAGEMENT_EXPERIENCE_DETAILS
alter table HRMANAGEMENT_EXPERIENCE_DETAILS add constraint FK_HRMANAGEMENT_EXPERIENCE_DETAILS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_EXPERIENCE_DETAILS_CODE on HRMANAGEMENT_EXPERIENCE_DETAILS (CODE_ID)^
-- end HRMANAGEMENT_EXPERIENCE_DETAILS
-- begin HRMANAGEMENT_SALARY_DETAILS
alter table HRMANAGEMENT_SALARY_DETAILS add constraint FK_HRMANAGEMENT_SALARY_DETAILS_CODE foreign key (CODE_ID) references HRMANAGEMENT_ADD_EMPLOYEE(ID)^
create index IDX_HRMANAGEMENT_SALARY_DETAILS_CODE on HRMANAGEMENT_SALARY_DETAILS (CODE_ID)^
-- end HRMANAGEMENT_SALARY_DETAILS
