-- begin TASK_PROPERTY
alter table TASK_PROPERTY add constraint FK_TASK_PROPERTY_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
alter table TASK_PROPERTY add constraint FK_TASK_PROPERTY_SELLER foreign key (SELLER_ID) references TASK_SELLER(ID)^
create index IDX_TASK_PROPERTY_IMAGE_FILE on TASK_PROPERTY (IMAGE_FILE_ID)^
create index IDX_TASK_PROPERTY_SELLER on TASK_PROPERTY (SELLER_ID)^
-- end TASK_PROPERTY
-- begin TASK_BOOKING
alter table TASK_BOOKING add constraint FK_TASK_BOOKING_SELLER_INFO foreign key (SELLER_INFO_ID) references TASK_SELLER(ID)^
create index IDX_TASK_BOOKING_SELLER_INFO on TASK_BOOKING (SELLER_INFO_ID)^
-- end TASK_BOOKING
-- begin TASK_SALES_LISTING
alter table TASK_SALES_LISTING add constraint FK_TASK_SALES_LISTING_TRANSACTION foreign key (TRANSACTION_ID) references TASK_TRANSACTION(ID)^
create index IDX_TASK_SALES_LISTING_TRANSACTION on TASK_SALES_LISTING (TRANSACTION_ID)^
-- end TASK_SALES_LISTING
