-- begin BICYCLEAPP_CLIENT
create unique index IDX_BICYCLEAPP_CLIENT_UNIQ_EMAIL on BICYCLEAPP_CLIENT (EMAIL) ^
create unique index IDX_BICYCLEAPP_CLIENT_UNIQ_PHONE_NUMBER on BICYCLEAPP_CLIENT (PHONE_NUMBER) ^
-- end BICYCLEAPP_CLIENT
-- begin BICYCLEAPP_MECHANIC
alter table BICYCLEAPP_MECHANIC add constraint FK_BICYCLEAPP_MECHANIC_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BICYCLEAPP_MECHANIC_USER on BICYCLEAPP_MECHANIC (USER_ID)^
-- end BICYCLEAPP_MECHANIC
-- begin BICYCLEAPP_SPARE_PART
create unique index IDX_BICYCLEAPP_SPARE_PART_UNIQ_TITLE on BICYCLEAPP_SPARE_PART (TITLE) ^
-- end BICYCLEAPP_SPARE_PART
-- begin BICYCLEAPP_ORDER
alter table BICYCLEAPP_ORDER add constraint FK_BICYCLEAPP_ORDER_CLIENT foreign key (CLIENT_ID) references BICYCLEAPP_CLIENT(ID)^
alter table BICYCLEAPP_ORDER add constraint FK_BICYCLEAPP_ORDER_MECHANICS foreign key (MECHANICS_ID) references BICYCLEAPP_MECHANIC(ID)^
alter table BICYCLEAPP_ORDER add constraint FK_BICYCLEAPP_ORDER_PARTS foreign key (PARTS_ID) references BICYCLEAPP_SPARE_PART(ID)^
create index IDX_BICYCLEAPP_ORDER_CLIENT on BICYCLEAPP_ORDER (CLIENT_ID)^
create index IDX_BICYCLEAPP_ORDER_MECHANICS on BICYCLEAPP_ORDER (MECHANICS_ID)^
create index IDX_BICYCLEAPP_ORDER_PARTS on BICYCLEAPP_ORDER (PARTS_ID)^
-- end BICYCLEAPP_ORDER
