alter table EMS_CONTACT add constraint FK_EMS_CONTACT_ORGANIZATION foreign key (ORGANIZATION_ID) references EMS_ORGANIZATION(ID);
create index IDX_EMS_CONTACT_ORGANIZATION on EMS_CONTACT (ORGANIZATION_ID);
