alter table HRMANAGEMENT_NOMINEES_DETAILS alter column MINOR_NOMINEE_ID rename to MINOR_NOMINEE_ID__U93309 ;
alter table HRMANAGEMENT_NOMINEES_DETAILS alter column MINOR_NOMINEE_ID__U93309 set null ;
alter table HRMANAGEMENT_NOMINEES_DETAILS add column MINOR_NOMINEE integer ^
update HRMANAGEMENT_NOMINEES_DETAILS set MINOR_NOMINEE = 10 where MINOR_NOMINEE is null ;
alter table HRMANAGEMENT_NOMINEES_DETAILS alter column MINOR_NOMINEE set not null ;
