alter table HRMANAGEMENT_ADD_EMPLOYEE add constraint FK_HRMANAGEMENT_ADD_EMPLOYEE_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_HRMANAGEMENT_ADD_EMPLOYEE_IMAGE_FILE on HRMANAGEMENT_ADD_EMPLOYEE (IMAGE_FILE_ID);
