alter table BICYCLEAPPS1_MECHANICS add constraint FK_BICYCLEAPPS1_MECHANICS_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_BICYCLEAPPS1_MECHANICS_USER on BICYCLEAPPS1_MECHANICS (USER_ID);
