alter table BICYCLEAPPS1_ODER_SPARE_PART_LINK add constraint FK_ODESPAPAR_ODER foreign key (ODER_ID) references BICYCLEAPPS1_ODER(ID);
alter table BICYCLEAPPS1_ODER_SPARE_PART_LINK add constraint FK_ODESPAPAR_SPARE_PART foreign key (SPARE_PART_ID) references BICYCLEAPPS1_SPARE_PART(ID);
