alter table BICYCLEAPPS1_ODER add constraint FK_BICYCLEAPPS1_ODER_CLIENT foreign key (CLIENT_ID) references BICYCLEAPPS1_CLIENT(ID);
alter table BICYCLEAPPS1_ODER add constraint FK_BICYCLEAPPS1_ODER_MECHANICS foreign key (MECHANICS_ID) references BICYCLEAPPS1_MECHANICS(ID);
alter table BICYCLEAPPS1_ODER add constraint FK_BICYCLEAPPS1_ODER_PARTS foreign key (PARTS_ID) references BICYCLEAPPS1_SPARE_PART(ID);
create index IDX_BICYCLEAPPS1_ODER_CLIENT on BICYCLEAPPS1_ODER (CLIENT_ID);
create index IDX_BICYCLEAPPS1_ODER_MECHANICS on BICYCLEAPPS1_ODER (MECHANICS_ID);
create index IDX_BICYCLEAPPS1_ODER_PARTS on BICYCLEAPPS1_ODER (PARTS_ID);
