alter table TASK_SALES_LISTING add constraint FK_TASK_SALES_LISTING_TRANSACTION foreign key (TRANSACTION_ID) references TASK_TRANSACTION(ID);
create index IDX_TASK_SALES_LISTING_TRANSACTION on TASK_SALES_LISTING (TRANSACTION_ID);
